### ISSUE TITLE
The moving of this project has marked the PRs excluded for Hacktoberfest. 

### ISSUE THREAD

**Issue by DearDhruv** [ietebitmesra/Hacktoberfest_21#1]
![image](https://user-images.githubusercontent.com/1201239/136102786-e63f2174-1771-4739-adba-a40d306f3e7e.png)

Kindly move back!
thanks.

**Comment by hrit-ik** [comment]
Due to some unpredictable issue we have to shift our project to this new repo. Task 3 will continue here and all PR's given in this repo will be counted. Sorry for inconvenience.

**Comment by DearDhruv** [comment]
Yeh, It's your repository, can do however you need. 
**The old PRs are definitely gone!** 

Thanks.
