### ISSUE TITLE
Add My List Section of Favourite movies and tv shows

### ISSUE THREAD

**Issue by pulkit2910-bit** [ietebitmesra/Hacktoberfest_21#139]
I want to solve this issue......please assign it to me **ONLY** :)

**Comment by hrit-ik** [comment]
ok😂
Assigned.

**Comment by pulkit2910-bit** [comment]
User can add a movie or tv show to their list

**Comment by pulkit2910-bit** [comment]
We can use local storage......I will try to make it....but if I am not able to do it then we can discard this issue :)

**Comment by pulkit2910-bit** [comment]
I have made a PR.....please have a look at it if it is working properly or not
