### ISSUE TITLE
Enable switching between different categories of Movies and TV shows in the Discover tab

### ISSUE THREAD

**Issue by Cedricmuuo** [ietebitmesra/Hacktoberfest_21#144]
Under the discover tab, I suppose a user should be able to switch between the different categories when viewing content. Currently, clicking on a different category does not switch to it but instead, it chooses it as an additional filter.  The user has to manually unclick the previous category to 'unselect' the content from the category.

I could rework it to only show content under a specific category when the category is switched to.

**Comment by hrit-ik** [comment]
It is made to work that way. As a single movie can be of many genre, we get input from user for genre(s) and then give result based on all selected genre(s). 
Thanks for your interest :)
