### ISSUE TITLE
Change breakpoints on movie page main info.

### ISSUE THREAD

**Issue by hrit-ik** [ietebitmesra/Hacktoberfest_21#157]
<img width="1343" alt="Screenshot 2021-10-16 at 5 14 36 PM" src="https://user-images.githubusercontent.com/48386941/137586042-46283d71-0361-4c70-a51c-0d46f27c2d2e.png">

<img width="1404" alt="Screenshot 2021-10-16 at 5 15 11 PM" src="https://user-images.githubusercontent.com/48386941/137586049-de56ab86-e7fc-4e5f-866a-a66eca13452d.png">

Make it look like 2nd image. (make same breakpoints)

**Comment by pulkit2910-bit** [comment]
![image](https://user-images.githubusercontent.com/77522350/137587325-29fde811-a55b-4880-8198-88319eefd8a9.png)

done

**Comment by hrit-ik** [comment]
Great!
Congrats you were the 100th pr😂

**Comment by pulkit2910-bit** [comment]
Hey man! It's working fine

**Comment by hrc-init** [comment]
Nah, its not on my system. Let it be now, I will fix it later along with other prs.
