### ISSUE TITLE
Navbar items not visible on mobile/lower page width

### ISSUE THREAD

**Issue by VivekPattanayak** [ietebitmesra/Hacktoberfest_21#161]
![image](https://user-images.githubusercontent.com/56192025/137593735-a831193c-9b40-4428-878c-12ba9d511ccf.png)

Navbar items are not visible at all on mobile + on pc they disappear if the page is below a certain width.

**Comment by VivekPattanayak** [comment]
Are others also facing this issue? Pl confirm

**Comment by hrit-ik** [comment]
Assigned :)

**Comment by panchoroo** [comment]
I can take a look at it?

**Comment by hrit-ik** [comment]
> I can take a look at it?

Assigned.
Thanks for your interest :)
