### ISSUE TITLE
Add any 6 popular/favorite movies on movies home page (like on TV page)

### ISSUE THREAD

**Issue by hrit-ik** [ietebitmesra/Hacktoberfest_21#28]

**Comment by pulkit2910-bit** [comment]
I want to work on this issue

**Comment by hrit-ik** [comment]
OK, I have assigned you both.
Thanks for your interest.

**Comment by hrit-ik** [comment]
No, you can add your favourite movies manually like TV page.
We will leave the api for explore page.

**Comment by pulkit2910-bit** [comment]
> @Simple-Saviour you add it on home page manually. @pulkit2910-bit you can use the api to display trending movies on explore page.

ok so you are saying to display all trending movies and series on the explore.......ok will work on that

**Comment by hrit-ik** [comment]
yes

**Comment by Simple-Saviour** [comment]
I have added the list of the movies and made it responsive too
