### ISSUE TITLE
hamburger menu not working on movies page.

### ISSUE THREAD

**Issue by hrit-ik** [ietebitmesra/Hacktoberfest_21#29]

**Comment by pulkit2910-bit** [comment]
It is caused by the typing animation in the home page....so can i work on this

**Comment by hrit-ik** [comment]
I have fixed this bug. You can now work on other issues :)

**Comment by hrit-ik** [comment]
And thanks for your active participation in the project.
Your contributions will definitely be recognized :)

**Comment by pulkit2910-bit** [comment]
> And thanks for your active participation in the project. Your contributions will definitely be recognized :)

My pleasure
