### ISSUE TITLE
Only 5 seasons being shown regardless of how many seasons show has

### ISSUE THREAD

**Issue by VivekPattanayak** [ietebitmesra/Hacktoberfest_21#33]
The season count is only displaying 5 seasons regardless of how many seasons a show has (<=5 or >5).

![SeasonOnlytill5](https://user-images.githubusercontent.com/56192025/136650703-d30ec447-0165-445a-a9b2-f482b6a62528.png)

I would like to be assigned to fix this issue.

**Comment by VivekPattanayak** [comment]
Can I please be assigned this issue?

**Comment by hrit-ik** [comment]
I have actually assigned it to someone, but they have not made a pr till now. So, I am now assigning it to you now.
Thanks for your interest :)
