### ISSUE TITLE
Link the season link to its episode table.

### ISSUE THREAD

**Issue by hrit-ik** [ietebitmesra/Hacktoberfest_21#36]
<img width="1105" alt="Screenshot 2021-10-09 at 5 35 14 PM" src="https://user-images.githubusercontent.com/48386941/136657134-43981ac7-7836-41d6-b522-0b01bfed1a58.png">

In the above screenshot only Season one's episodes are displayed for all shows. It would be great if you could link the season link to display the particular table.

**Comment by hrit-ik** [comment]
Thanks for your active participation :)
Assigned.

**Comment by VivekPattanayak** [comment]
Sent a pr for the same.
