### ISSUE TITLE
Cast not being shown on clicking the 'cast' button (TV Shows)

### ISSUE THREAD

**Issue by VivekPattanayak** [ietebitmesra/Hacktoberfest_21#59]
On clicking the 'cast' button , the cast of the show should be shown along with their pictures/card . As of now, nothing happens on clicking the cast button.

**Comment by hrit-ik** [comment]
Assigned.

**Comment by hrit-ik** [comment]
Also please remove the season button.

**Comment by VivekPattanayak** [comment]
Done. Sent a pr for it .
