### ISSUE TITLE
Add carousel slides in explore tab

### ISSUE THREAD

**Issue by pulkit2910-bit** [ietebitmesra/Hacktoberfest_21#60]
Carousel slides for popular tv shows and movies

**Comment by Nupurgit2000** [comment]
Hey, I want to contribute to this issue. Pls assign this to me.

**Comment by pulkit2910-bit** [comment]
> Please make pr for another pending issue which is assigned to you. Meanwhile if no other person shows interest in this issue I will assign it to you.

Ok 
Fine by me😇

**Comment by hrit-ik** [comment]
@Yashashree-Navander @Nupurgit2000 I have now assigned you both.
Thanks for your interest :)

**Comment by pulkit2910-bit** [comment]
It seems that no one has done yet so can I be assigned this ;)

**Comment by pulkit2910-bit** [comment]
I was trying to solve this but was not able to do it :(
So somebody else is welcome to solve this issue :)
